sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 172.16.64.128
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: 172.16.64.128
    port: 6379
    password: redis
    database: 0
  fastdfs:
    props-file-path: "fdfs_client.properties"
    http-prefix: "http"
  wechat:
    appid: wxf6a1f7bc1c0b3c1d
    secret: c9a27465627759a28acce4fcb10fca0c


